### ISSUE TITLE
AFHTTPSessionManager+AutoRetry.m wrong condition

### ISSUE THREAD

**Issue by kubatru** [shaioz/AFNetworking-AutoRetry#13]
In **requestUrlWithAutoRetry** in **if** statement is **if (retriesRemainingCount > 0)** but it should be **(retriesRemaining > 0)**. In your case the new attempt will never be executed since the **retryOperationDict** is not exist.

**Comment by lexicalunit** [comment]
I am having the same issue you are probably having where no matter what retry count I use, the `AFHTTPSessionManager+AutoRetry` category does not actually do any retries. I believe this is because of a small typo in the creation of the `taskDict` property. In the block, the key used for fetching the task information (such as `retriesRemainingCount` as you have noted) is `taskcreatorCopy`. However, below the block, where `taskDict` is updated, the key used is `task` instead of `taskcreatorCopy`. I believe this is a typo. Fixing it resolves the issue and causes retries to be preformed as expected.

**Comment by lexicalunit** [comment]
I just submitted PR #14 which should resolve this issue.

**Comment by jold** [comment]
@shivanraptor has repaired this issue in his last commit :) enjoy

**Comment by lexicalunit** [comment]
:+1:
