### ISSUE TITLE
AFHTTPSessionManager+AutoRetry not work?

### ISSUE THREAD

**Issue by BOZ88** [shaioz/AFNetworking-AutoRetry#18]
``` code
NSMutableDictionary *retryOperationDict = self.tasksDict[taskcreatorCopy];
```

change to 

``` code
NSMutableDictionary *retryOperationDict = self.tasksDict[task];
```

will do run the retry logic, I don't know whether I misunderstand or the logic is not correct.

**Comment by bryanOrtiz** [comment]
This fixed an issue I was seeing where a failure would cause an infinite loop. +1

**Comment by jold** [comment]
The copy of object is created as it is used insight the asynchronous call (the retryBlock), there is no guaranty that the original object will still exist. This was causing the app crash when operating on lazy connection. 

So the taskcreatorCopy is copied because taskCreator might be already released, while should be used insight retryBlock.
